version: '3'

services:
    mysql-server:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password 
            MYSQL_DATABASE: logindb

    loginapp:
        build:
            dockerfile: Dockerfile 
            context: ./
        environment: 
            MSHOST: mysql-server
            MSUSER: root
            MSPASSWORD: password
            MSDATABASE: logindb
            SERVERPORT: 8888
            WAIT_HOSTS: mysql-server:3306
            WAIT_HOSTS_TIMEOUT: 90
        ports:
            - "8888:8888"
        depends_on: 
            - mysql-server